computerinventory/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^inventory/', include('inventory.urls')),
]

inventory/urls.py
from django.conf.urls import url

from . import views

app_name = 'inventory'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<inventory_id>[0-9]+)/$', views.inventory, name='inventory'),
    url(r'^addinventory/$', views.add_inventory, name='addinventory'),
    url(r'^(?P<inventory_id>[0-9]+)/addcomputer/$', views.add_computer, name='addcomputer'),
    url(r'^(?P<inventory_id>[0-9]+)/editcomputer/(?P<computer_id>[0-9]+)/$', views.edit_computer, name='editcomputer'),
    url(r'^(?P<inventory_id>[0-9]+)/deletecomputer/(?P<computer_id>[0-9]+)/$', views.delete_computer, name='deletecomputer'),
]

inventory/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Basic inventory model
class Inventory(models.Model):
    name = models.CharField(max_length=256)

# Basic computer model
class Computer(models.Model):
    inventory = models.ForeignKey(Inventory, on_delete=models.CASCADE)
    manufacturer = models.CharField(max_length=256)
    serial = models.CharField(max_length=256)
    comments= models.CharField(max_length=1024)

inventory/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse

from .models import Inventory, Computer
from .edit_computer_form import EditComputerForm

# Index page just contains a list of inventories.
def index(request):
    inventories = Inventory.objects.all()
    context = { 'inventories': inventories }
    return render(request, 'inventory/index.html', context)

# Inventory page lists computers in a given inventory.
def inventory(request, inventory_id):
    # First get the associated inventory.
    try:
        inventory = Inventory.objects.get(pk=inventory_id)
    except Inventory.DoesNotExist:
        raise Http404("Inventory does not exist")

    # Get and render the list of computers.
    computers = Computer.objects.filter(inventory=inventory_id)
    context = { 'inventory': inventory, 'computers': computers }
    return render(request, 'inventory/inventory.html', context)

# Returns form for adding a new inventory.
def add_inventory(request):
    # Render form if GET is used.
    if request.method == 'GET':
        return render(request, 'inventory/addinventory.html', {})
    # Add a new inventory if POST is used.
    elif request.method == 'POST':
        inventory = Inventory(name=request.POST['name'])
        inventory.save();
        return HttpResponseRedirect(reverse('inventory:index'))

# Form for adding a new computer to a inventory.
def add_computer(request, inventory_id):
    # First get the inventory (necessary for both get and post).
    try:
        inventory = Inventory.objects.get(pk=inventory_id)
    except Inventory.DoesNotExist:
        raise Http404("Inventory does not exist")

    # Render the form if GET is used
    if request.method == 'GET':
        context = { 'inventory': inventory }
        return render(request, 'inventory/addcomputer.html', context)
    # Add new computer to an inventory if POST is used
    elif request.method == 'POST':
        # Create the computer in the correct inventory.
        computer = Computer(serial=request.POST['serial'], manufacturer=request.POST['manufacturer'], comments=request.POST['comments'], inventory=inventory)
        computer.save()
        return HttpResponseRedirect(reverse('inventory:inventory', args=(inventory_id,)))

# Form for editing a computers info.
def edit_computer(request, inventory_id, computer_id):
    # Render form if GET is used.
    if request.method == 'GET':
        form = EditComputerForm();
        context = { 'edit_form': form }
        return render(request, 'inventory/editcomputer.html', context)
    # Update the fields, if any, and save the computer again.
    if request.method == 'POST':
        computer = Computer.objects.get(pk=computer_id)
        if request.POST['serial']:
            computer.serial = request.POST['serial']
        if request.POST['manufacturer']:
            computer.manufacturer = request.POST['manufacturer']
        if request.POST['comments']:
            computer.comments = request.POST['comments']

        computer.save()
        return HttpResponseRedirect(reverse('inventory:inventory', args=(inventory_id,)))

# Endpoint for deleting a computer.
def delete_computer(request, inventory_id, computer_id):
    try:
        computer = Computer.objects.get(pk=computer_id)
    except Computer.DoesNotExist:
        raise Http404("Computer does not exist")

    computer.delete()

    return HttpResponseRedirect(reverse('inventory:inventory', args=(inventory_id,)))

inventory/templates/inventory/addcomputer.html
{% extends "base.html" %}

{% block content %}
<h1>New Computer</h1>
{% if inventory %}
    <h2>{{ inventoryi.name }} </h2>
{% endif %}

<form action="{% url 'inventory:addcomputer' inventory.id %}" method="post">
{% csrf_token %}
    <label for="serial">Serial</label>
    <input type="text" name="serial" id="serial" placeholder="Serial #" />
    <label for="manufacturer">manufacturer</label>
    <input type="text" name="manufacturer" id="manufacturer" placeholder="Manufacturer" />
    <label for="Comments">Comments</label>
    <input type="text" name="comments" id="comments" placeholder="Comment" />
    <input type="submit"/>
</form>
{% endblock %}

inventory/templates/inventory/addinventory.html
{% extends "base.html" %}

{% block content %}
<h1>New Inventory</h1>

<form action="{% url 'inventory:addinventory' %}" method="post">
{% csrf_token %}
    <label for="invName">Name</label>
    <input type="text" name="name" id="invName" placeholder="New Inventory" />
    <input type="submit"/>
</form>
{% endblock %}

inventory/templates/inventory/base.html
{% load static %}


<html>
<head>
    <title>Computer Inventory</title>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'inventory/style.css' %}" />

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" ></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" ></script>

</head>
<body>
    <nav class="navbar navbar-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'inventory:index' %}" >Computer Inventory</a>
        </div>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

inventory/templates/inventory/editcomputer.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}
{% crispy edit_form edit_form.helper %}

{% endblock %}

inventory/templates/inventory/index.html
{% extends "base.html" %}

{% block content %}
<div id="inventory-header">
    <h4 id="inventory-title">My Inventories</h4>
    <a id="button-add-computer" class="btn btn-primary btn-sm" role="button" href="{% url 'inventory:addinventory' %}">Add Inventory</a>
</div>
<hr style="clear: both"></hr>
{% if inventories %}
    <ul>
    {% for inventory in inventories %}
        <li><a href="{% url 'inventory:inventory' inventory.id %}">
                {{inventory.name}}
        </a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No inventories yet.</p>
{% endif %}
{% endblock %}

inventory/templates/inventory/inventory.html
{% extends "base.html" %}

{% block content %}
{% if inventory %}
<div id="inventory-header">
    <h4 id="inventory-title">{{inventory.name}}</h4>
    <a id="button-add-computer" class="btn btn-primary btn-sm" role="button" href="{% url 'inventory:addcomputer' inventory.id  %}">Add Computer</a>
</div>
{% endif %}
{% if computers %}
    <table class="table">
        <thead>
            <tr>
                <th>Serial #</th>
                <th>Manufacturer</th>
                <th>Comments</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for computer in computers %}
            <tr>
                <td>{{computer.serial}}</td>
                <td>{{computer.manufacturer}}</td>
                <td>{{computer.comments}}</td>
                <td>
                    <p>
                        <a href="{% url 'inventory:editcomputer' inventory.id computer.id %}" >Edit</a>
                        &#8231
                        <a href="{% url 'inventory:deletecomputer' inventory.id computer.id %}" >Delete</a>
                    </p>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <div id="no-computer">
        <hr></hr>
        <p>No computers yet.</p>
    </div>
{% endif %}
{% endblock %}